// Generated by CoffeeScript 1.12.8
(function() {
  var description, note, title, url;

  title = encodeURIComponent(document.title);

  url = encodeURIComponent(location.href);

  note = '';

  description = document.getElementsByName('description')[0];

  if (description) {
    note = encodeURIComponent(description.content);
  }

  window.open('http://localhost:5000/a?name=' + title + '&note=' + note + '&url=' + url);

}).call(this);
